const translations = {
  en: {
    home: "Home",
    about: "About Us",
    employers: "Employers",
    candidates: "Candidates",
    services: "Services",
    contact: "Contact",
    cta: "Start a Conversation",
    servicesCta: "Explore Services",
    homeEyebrow: "International Recruitment & Workforce Solutions",
    homeSubtitle: "Connecting Talent. Building Futures.",
    homeCopy: "A Munich-based recruitment partner helping employers in Germany and Europe connect with qualified international professionals through a clear, complete and human recruitment process.",
    whyKicker: "Why Talorynex",
    whyTitle: "A specialist team with proven international recruitment experience.",
    whyCopy: "For 4 years we have supported employers and candidates through practical recruitment, relocation guidance and communication with relevant offices.",
    homeStatOne: "Years of recruiting experience",
    homeStatTwo: "Candidates successfully supported",
    homeStatThreeValue: "End-to-End",
    homeStatThree: "Complete recruitment process",
    homeStatFourValue: "Authorities",
    homeStatFour: "Communication with the foreigners office",
    focusTitle: "Recruitment that feels organized, personal and global.",
    focusCopy: "Clear visual sections, separate pages, and focused service paths now make the website easier to understand and navigate.",
    focusEmployerTitle: "Employer Partnerships",
    focusEmployerCopy: "We work closely with companies to understand hiring needs, candidate profiles and onboarding requirements.",
    focusCandidateTitle: "Candidate Support",
    focusCandidateCopy: "We guide candidates through applications, interviews, relocation preparation and workplace integration.",
    focusDocTitle: "Documentation & Offices",
    focusDocCopy: "We support coordination and communication with relevant authorities, including the foreigners office where needed.",
    processKicker: "Process",
    processTitle: "From first contact to successful integration.",
    processCopy: "The site now mirrors the real recruitment journey: consultation, sourcing, documentation and onboarding.",
    processCta: "View the process",
    contactUs: "Contact us",
    aboutEyebrow: "About Talorynex",
    aboutHeroTitle: "Professional recruitment built for international teams.",
    aboutHeroCopy: "We are a team of recruitment specialists focused on reliable international hiring, candidate care and practical workforce solutions.",
    aboutCompanyKicker: "Our Company",
    aboutCompanyTitle: "Experienced, structured and people-focused.",
    aboutCompanyCopyOne: "Talorynex International Recruiting has supported international recruitment processes for 4 years and helped more than 400 candidates from different countries move through career, relocation and integration steps.",
    aboutCompanyCopyTwo: "Our work combines employer consulting, candidate sourcing, application support, relocation orientation and communication with relevant offices, including the foreigners office when needed.",
    aboutStatOne: "Years active in international recruitment",
    aboutStatTwo: "Candidates supported from different countries",
    aboutStatThreeValue: "Munich",
    aboutStatThree: "Based in Germany",
    aboutStatFourValue: "Complete",
    aboutStatFour: "Recruitment and integration support",
    employersEyebrow: "For Employers",
    employersHeroTitle: "Reliable international hiring support.",
    employersHeroCopy: "We help companies define needs, source candidates, coordinate communication and prepare for successful onboarding.",
    empCardOneTitle: "Recruitment Solutions",
    empCardOneCopy: "Focused search and selection for qualified, motivated international professionals.",
    empCardTwoTitle: "Talent Acquisition",
    empCardTwoCopy: "Candidate outreach, screening, shortlisting and communication built for clear hiring pipelines.",
    empCardThreeTitle: "Workforce Support",
    empCardThreeCopy: "Practical support around candidate readiness, documentation awareness and integration.",
    empCardFourTitle: "International Hiring",
    empCardFourCopy: "Cross-border recruitment support for employers building stable teams in Germany and Europe.",
    empValueKicker: "Employer Value",
    empValueTitle: "A structured partner for demanding hiring needs.",
    empValueCopy: "Talorynex helps employers move from profile definition to candidate selection and integration with a practical, transparent process.",
    empValueCta: "Request candidates",
    candidatesEyebrow: "For Candidates",
    candidatesHeroTitle: "Your next career step, guided with care.",
    candidatesHeroCopy: "We support international professionals with applications, relocation preparation and integration guidance for working in Germany.",
    candJourneyKicker: "Candidate Journey",
    candJourneyTitle: "Clear support before, during and after the application.",
    candStepOneTitle: "Career Opportunities",
    candStepOneCopy: "Access relevant opportunities with employers seeking qualified international professionals.",
    candStepTwoTitle: "Application Support",
    candStepTwoCopy: "Prepare candidate profiles, documents and interviews with stronger clarity.",
    candStepThreeTitle: "Relocation Assistance",
    candStepThreeCopy: "Receive orientation for moving, working and settling in Germany.",
    candStepFourTitle: "Integration Guidance",
    candStepFourCopy: "Understand workplace expectations and start with confidence.",
    servicesEyebrow: "Services",
    servicesHeroTitle: "Complete recruitment and workforce solutions.",
    servicesHeroCopy: "From talent sourcing to documentation support and integration, our services are designed for serious international hiring.",
    servCardOneTitle: "International Recruitment",
    servCardOneCopy: "End-to-end support for companies seeking qualified professionals beyond local markets.",
    servCardTwoTitle: "Talent Sourcing",
    servCardTwoCopy: "Targeted sourcing strategies for motivated candidates aligned with employer requirements.",
    servCardThreeTitle: "Workforce Solutions",
    servCardThreeCopy: "Support for planning, hiring and integrating international talent with confidence.",
    servCardFourTitle: "Employer Consulting",
    servCardFourCopy: "Practical guidance on international hiring workflows and candidate expectations.",
    servDocKicker: "Documentation",
    servDocTitle: "Support with offices and required communication.",
    servDocCopy: "We help coordinate communication with relevant authorities, including the foreigners office, when the recruitment process requires it.",
    faqKicker: "FAQ",
    faqTitle: "Questions employers and candidates often ask.",
    faqOneTitle: "Do you support the full process?",
    faqOneCopy: "Yes. We support recruitment, candidate communication, documentation awareness and onboarding preparation.",
    faqTwoTitle: "Do you help candidates relocate?",
    faqTwoCopy: "Yes. We provide relocation orientation and integration guidance for candidates preparing to work in Germany.",
    faqThreeTitle: "Do you work with employers?",
    faqThreeCopy: "Yes. We help employers define needs, source candidates and prepare the hiring process.",
    faqFourTitle: "How do we start?",
    faqFourCopy: "Send us a short inquiry through the contact page and we will respond with next steps.",
    contactEyebrow: "Contact",
    contactHeroTitle: "Let us discuss your recruitment goals.",
    contactHeroCopy: "Send an inquiry as an employer, candidate or partner. The form opens your email app with a prepared message.",
    contactPanelTitle: "Munich, Germany",
    contactEmailLabel: "Email:",
    contactLocation: "Location: Munich, Germany",
    contactServicesLine: "Services: Employers, candidates, recruitment and relocation support",
    formName: "Name",
    formEmail: "Email",
    formPhone: "Phone",
    formType: "I am contacting as",
    formTypeEmployer: "Employer",
    formTypeCandidate: "Candidate",
    formTypeOther: "Other",
    formSubject: "Subject",
    formMessage: "Message",
    formSubmit: "Send Inquiry",
    formNote: "This static GitHub Pages form opens your email app. Later, we can connect Formspree or another form service for direct inbox delivery.",
    footerRights: "© 2026 Talorynex International Recruiting. All rights reserved.",
    footerShort: "© 2026 Talorynex International Recruiting."
  },
  bs: {
    home: "Početna",
    about: "O nama",
    employers: "Poslodavci",
    candidates: "Kandidati",
    services: "Usluge",
    contact: "Kontakt",
    cta: "Započnite razgovor",
    servicesCta: "Pogledajte usluge",
    homeEyebrow: "Međunarodna regrutacija i rješenja za radnu snagu",
    homeSubtitle: "Povezujemo talente. Gradimo budućnost.",
    homeCopy: "Partner za regrutaciju iz Minhena koji pomaže poslodavcima u Njemačkoj i Evropi da se povežu sa kvalifikovanim međunarodnim stručnjacima kroz jasan, kompletan i ljudski proces regrutacije.",
    whyKicker: "Zašto Talorynex",
    whyTitle: "Tim stručnjaka sa dokazanim iskustvom u međunarodnoj regrutaciji.",
    whyCopy: "Već 4 godine podržavamo poslodavce i kandidate kroz praktičnu regrutaciju, smjernice za preseljenje i komunikaciju sa relevantnim uredima.",
    homeStatOne: "Godine iskustva u regrutaciji",
    homeStatTwo: "Uspješno podržanih kandidata",
    homeStatThreeValue: "Kompletno",
    homeStatThree: "Cjelokupan proces regrutacije",
    homeStatFourValue: "Institucije",
    homeStatFour: "Komunikacija sa uredom za strance",
    focusTitle: "Regrutacija koja je organizovana, lična i globalna.",
    focusCopy: "Jasne vizuelne sekcije, posebne stranice i fokusirane usluge čine web stranicu lakšom za razumijevanje i korištenje.",
    focusEmployerTitle: "Partnerstvo s poslodavcima",
    focusEmployerCopy: "Blisko sarađujemo s kompanijama kako bismo razumjeli potrebe zapošljavanja, profil kandidata i onboarding zahtjeve.",
    focusCandidateTitle: "Podrška kandidatima",
    focusCandidateCopy: "Vodimo kandidate kroz prijave, intervjue, pripremu za preseljenje i integraciju na radnom mjestu.",
    focusDocTitle: "Dokumentacija i uredi",
    focusDocCopy: "Podržavamo koordinaciju i komunikaciju sa relevantnim institucijama, uključujući ured za strance kada je potrebno.",
    processKicker: "Proces",
    processTitle: "Od prvog kontakta do uspješne integracije.",
    processCopy: "Stranica sada prikazuje stvarni proces regrutacije: konsultacije, sourcing, dokumentaciju i onboarding.",
    processCta: "Pogledajte proces",
    contactUs: "Kontaktirajte nas",
    aboutEyebrow: "O Talorynexu",
    aboutHeroTitle: "Profesionalna regrutacija za međunarodne timove.",
    aboutHeroCopy: "Mi smo tim stručnjaka za regrutaciju fokusiran na pouzdano međunarodno zapošljavanje, brigu o kandidatima i praktična rješenja za radnu snagu.",
    aboutCompanyKicker: "Naša kompanija",
    aboutCompanyTitle: "Iskusni, strukturirani i fokusirani na ljude.",
    aboutCompanyCopyOne: "Talorynex International Recruiting već 4 godine podržava međunarodne procese regrutacije i pomogao je za više od 400 kandidata iz različitih zemalja kroz karijeru, preseljenje i integraciju.",
    aboutCompanyCopyTwo: "Naš rad kombinuje savjetovanje poslodavaca, pronalazak kandidata, podršku pri prijavi, orijentaciju za preseljenje i komunikaciju sa relevantnim uredima, uključujući ured za strance kada je potrebno.",
    aboutStatOne: "Godine aktivnog rada u međunarodnoj regrutaciji",
    aboutStatTwo: "Kandidati podržani iz različitih zemalja",
    aboutStatThreeValue: "Minhen",
    aboutStatThree: "Baza u Njemačkoj",
    aboutStatFourValue: "Kompletno",
    aboutStatFour: "Podrška regrutaciji i integraciji",
    employersEyebrow: "Za poslodavce",
    employersHeroTitle: "Pouzdana podrška za međunarodno zapošljavanje.",
    employersHeroCopy: "Pomažemo kompanijama da definišu potrebe, pronađu kandidate, koordiniraju komunikaciju i pripreme uspješan onboarding.",
    empCardOneTitle: "Rješenja za regrutaciju",
    empCardOneCopy: "Ciljana potraga i selekcija kvalifikovanih i motivisanih međunarodnih stručnjaka.",
    empCardTwoTitle: "Pronalazak talenata",
    empCardTwoCopy: "Kontaktiranje, provjera, uži izbor i komunikacija s kandidatima za jasan proces zapošljavanja.",
    empCardThreeTitle: "Podrška radnoj snazi",
    empCardThreeCopy: "Praktična podrška oko spremnosti kandidata, dokumentacije i integracije.",
    empCardFourTitle: "Međunarodno zapošljavanje",
    empCardFourCopy: "Podrška prekograničnoj regrutaciji za poslodavce koji grade stabilne timove u Njemačkoj i Evropi.",
    empValueKicker: "Vrijednost za poslodavce",
    empValueTitle: "Strukturiran partner za zahtjevne potrebe zapošljavanja.",
    empValueCopy: "Talorynex pomaže poslodavcima da od definisanja profila do izbora kandidata i integracije idu kroz praktičan i transparentan proces.",
    empValueCta: "Zatražite kandidate",
    candidatesEyebrow: "Za kandidate",
    candidatesHeroTitle: "Vaš sljedeći karijerni korak, uz stručnu podršku.",
    candidatesHeroCopy: "Podržavamo međunarodne stručnjake kroz prijave, pripremu za preseljenje i integracijske smjernice za rad u Njemačkoj.",
    candJourneyKicker: "Put kandidata",
    candJourneyTitle: "Jasna podrška prije, tokom i nakon prijave.",
    candStepOneTitle: "Karijerne prilike",
    candStepOneCopy: "Pristup relevantnim prilikama kod poslodavaca koji traže kvalifikovane međunarodne stručnjake.",
    candStepTwoTitle: "Podrška pri prijavi",
    candStepTwoCopy: "Priprema profila kandidata, dokumenata i intervjua sa više jasnoće.",
    candStepThreeTitle: "Pomoć pri preseljenju",
    candStepThreeCopy: "Orijentacija za preseljenje, rad i život u Njemačkoj.",
    candStepFourTitle: "Integracijske smjernice",
    candStepFourCopy: "Razumijevanje očekivanja na radnom mjestu i sigurniji početak.",
    servicesEyebrow: "Usluge",
    servicesHeroTitle: "Kompletna regrutacija i rješenja za radnu snagu.",
    servicesHeroCopy: "Od pronalaska talenata do podrške dokumentaciji i integraciji, naše usluge su dizajnirane za ozbiljno međunarodno zapošljavanje.",
    servCardOneTitle: "Međunarodna regrutacija",
    servCardOneCopy: "Kompletna podrška kompanijama koje traže kvalifikovane stručnjake izvan lokalnog tržišta.",
    servCardTwoTitle: "Sourcing talenata",
    servCardTwoCopy: "Ciljane strategije pronalaska motivisanih kandidata usklađenih sa zahtjevima poslodavca.",
    servCardThreeTitle: "Rješenja za radnu snagu",
    servCardThreeCopy: "Podrška za planiranje, zapošljavanje i integraciju međunarodnih talenata.",
    servCardFourTitle: "Savjetovanje poslodavaca",
    servCardFourCopy: "Praktične smjernice za međunarodne procese zapošljavanja i očekivanja kandidata.",
    servDocKicker: "Dokumentacija",
    servDocTitle: "Podrška sa uredima i potrebnom komunikacijom.",
    servDocCopy: "Pomažemo u koordinaciji komunikacije sa relevantnim institucijama, uključujući ured za strance kada proces regrutacije to zahtijeva.",
    faqKicker: "FAQ",
    faqTitle: "Pitanja koja poslodavci i kandidati često postavljaju.",
    faqOneTitle: "Da li podržavate cijeli proces?",
    faqOneCopy: "Da. Podržavamo regrutaciju, komunikaciju s kandidatima, pregled dokumentacije i pripremu za onboarding.",
    faqTwoTitle: "Da li pomažete kandidatima pri preseljenju?",
    faqTwoCopy: "Da. Pružamo orijentaciju za preseljenje i integracijske smjernice za kandidate koji se pripremaju za rad u Njemačkoj.",
    faqThreeTitle: "Da li radite sa poslodavcima?",
    faqThreeCopy: "Da. Pomažemo poslodavcima da definišu potrebe, pronađu kandidate i pripreme proces zapošljavanja.",
    faqFourTitle: "Kako počinjemo?",
    faqFourCopy: "Pošaljite kratak upit preko kontakt stranice i odgovorit ćemo sa sljedećim koracima.",
    contactEyebrow: "Kontakt",
    contactHeroTitle: "Razgovarajmo o vašim ciljevima zapošljavanja.",
    contactHeroCopy: "Pošaljite upit kao poslodavac, kandidat ili partner. Forma otvara vašu email aplikaciju sa pripremljenom porukom.",
    contactPanelTitle: "Minhen, Njemačka",
    contactEmailLabel: "Email:",
    contactLocation: "Lokacija: Minhen, Njemačka",
    contactServicesLine: "Usluge: poslodavci, kandidati, regrutacija i podrška preseljenju",
    formName: "Ime i prezime",
    formEmail: "Email",
    formPhone: "Telefon",
    formType: "Kontaktiram kao",
    formTypeEmployer: "Poslodavac",
    formTypeCandidate: "Kandidat",
    formTypeOther: "Drugo",
    formSubject: "Naslov",
    formMessage: "Poruka",
    formSubmit: "Pošalji upit",
    formNote: "Ova statična GitHub Pages forma otvara vašu email aplikaciju. Kasnije možemo povezati Formspree ili drugi servis za direktno slanje u inbox.",
    footerRights: "© 2026 Talorynex International Recruiting. Sva prava zadržana.",
    footerShort: "© 2026 Talorynex International Recruiting."
  },
  de: {
    home: "Start",
    about: "Über uns",
    employers: "Arbeitgeber",
    candidates: "Kandidaten",
    services: "Leistungen",
    contact: "Kontakt",
    cta: "Gespräch starten",
    servicesCta: "Leistungen ansehen",
    homeEyebrow: "Internationale Personalvermittlung & Workforce Solutions",
    homeSubtitle: "Talente verbinden. Zukunft gestalten.",
    homeCopy: "Ein Recruiting-Partner aus München, der Arbeitgeber in Deutschland und Europa mit qualifizierten internationalen Fachkräften durch einen klaren, vollständigen und menschlichen Recruiting-Prozess verbindet.",
    whyKicker: "Warum Talorynex",
    whyTitle: "Ein Expertenteam mit nachgewiesener Erfahrung im internationalen Recruiting.",
    whyCopy: "Seit 4 Jahren unterstützen wir Arbeitgeber und Kandidaten durch praktisches Recruiting, Relocation-Orientierung und Kommunikation mit relevanten Stellen.",
    homeStatOne: "Jahre Recruiting-Erfahrung",
    homeStatTwo: "Erfolgreich unterstützte Kandidaten",
    homeStatThreeValue: "Ganzheitlich",
    homeStatThree: "Kompletter Recruiting-Prozess",
    homeStatFourValue: "Behörden",
    homeStatFour: "Kommunikation mit der Ausländerbehörde",
    focusTitle: "Recruiting, das organisiert, persönlich und international wirkt.",
    focusCopy: "Klare visuelle Bereiche, einzelne Seiten und fokussierte Servicepfade machen die Website leichter verständlich.",
    focusEmployerTitle: "Partnerschaften mit Arbeitgebern",
    focusEmployerCopy: "Wir arbeiten eng mit Unternehmen zusammen, um Einstellungsbedarf, Kandidatenprofile und Onboarding-Anforderungen zu verstehen.",
    focusCandidateTitle: "Kandidatenbetreuung",
    focusCandidateCopy: "Wir begleiten Kandidaten durch Bewerbungen, Interviews, Relocation-Vorbereitung und Integration am Arbeitsplatz.",
    focusDocTitle: "Dokumente & Behörden",
    focusDocCopy: "Wir unterstützen Koordination und Kommunikation mit relevanten Stellen, einschließlich der Ausländerbehörde, wenn erforderlich.",
    processKicker: "Prozess",
    processTitle: "Vom ersten Kontakt bis zur erfolgreichen Integration.",
    processCopy: "Die Website spiegelt nun den realen Recruiting-Prozess wider: Beratung, Sourcing, Dokumentation und Onboarding.",
    processCta: "Prozess ansehen",
    contactUs: "Kontakt aufnehmen",
    aboutEyebrow: "Über Talorynex",
    aboutHeroTitle: "Professionelles Recruiting für internationale Teams.",
    aboutHeroCopy: "Wir sind ein Team von Recruiting-Spezialisten mit Fokus auf zuverlässige internationale Einstellungen, Kandidatenbetreuung und praktische Workforce-Lösungen.",
    aboutCompanyKicker: "Unser Unternehmen",
    aboutCompanyTitle: "Erfahren, strukturiert und menschenorientiert.",
    aboutCompanyCopyOne: "Talorynex International Recruiting unterstützt seit 4 Jahren internationale Recruiting-Prozesse und hat mehr als 400 Kandidaten aus verschiedenen Ländern bei Karriere, Relocation und Integration begleitet.",
    aboutCompanyCopyTwo: "Unsere Arbeit verbindet Arbeitgeberberatung, Kandidatensuche, Bewerbungsunterstützung, Relocation-Orientierung und Kommunikation mit relevanten Stellen, einschließlich der Ausländerbehörde, wenn erforderlich.",
    aboutStatOne: "Jahre aktiv im internationalen Recruiting",
    aboutStatTwo: "Kandidaten aus verschiedenen Ländern unterstützt",
    aboutStatThreeValue: "München",
    aboutStatThree: "Standort in Deutschland",
    aboutStatFourValue: "Komplett",
    aboutStatFour: "Recruiting- und Integrationssupport",
    employersEyebrow: "Für Arbeitgeber",
    employersHeroTitle: "Zuverlässige Unterstützung für internationales Recruiting.",
    employersHeroCopy: "Wir helfen Unternehmen, Bedarf zu definieren, Kandidaten zu finden, Kommunikation zu koordinieren und erfolgreiches Onboarding vorzubereiten.",
    empCardOneTitle: "Recruiting-Lösungen",
    empCardOneCopy: "Gezielte Suche und Auswahl qualifizierter, motivierter internationaler Fachkräfte.",
    empCardTwoTitle: "Talent Acquisition",
    empCardTwoCopy: "Kandidatenansprache, Screening, Shortlisting und Kommunikation für klare Recruiting-Pipelines.",
    empCardThreeTitle: "Workforce Support",
    empCardThreeCopy: "Praktische Unterstützung rund um Kandidatenbereitschaft, Dokumente und Integration.",
    empCardFourTitle: "Internationales Recruiting",
    empCardFourCopy: "Grenzüberschreitende Recruiting-Unterstützung für Arbeitgeber, die stabile Teams in Deutschland und Europa aufbauen.",
    empValueKicker: "Mehrwert für Arbeitgeber",
    empValueTitle: "Ein strukturierter Partner für anspruchsvolle Einstellungsbedarfe.",
    empValueCopy: "Talorynex begleitet Arbeitgeber von der Profildefinition bis zur Kandidatenauswahl und Integration mit einem praktischen, transparenten Prozess.",
    empValueCta: "Kandidaten anfragen",
    candidatesEyebrow: "Für Kandidaten",
    candidatesHeroTitle: "Ihr nächster Karriereschritt, professionell begleitet.",
    candidatesHeroCopy: "Wir unterstützen internationale Fachkräfte bei Bewerbungen, Relocation-Vorbereitung und Integration für die Arbeit in Deutschland.",
    candJourneyKicker: "Kandidatenreise",
    candJourneyTitle: "Klare Unterstützung vor, während und nach der Bewerbung.",
    candStepOneTitle: "Karrierechancen",
    candStepOneCopy: "Zugang zu relevanten Möglichkeiten bei Arbeitgebern, die qualifizierte internationale Fachkräfte suchen.",
    candStepTwoTitle: "Bewerbungsunterstützung",
    candStepTwoCopy: "Vorbereitung von Kandidatenprofilen, Dokumenten und Interviews mit mehr Klarheit.",
    candStepThreeTitle: "Relocation-Unterstützung",
    candStepThreeCopy: "Orientierung für Umzug, Arbeit und Ankommen in Deutschland.",
    candStepFourTitle: "Integrationsbegleitung",
    candStepFourCopy: "Arbeitsplatzanforderungen verstehen und sicher starten.",
    servicesEyebrow: "Leistungen",
    servicesHeroTitle: "Komplette Recruiting- und Workforce-Lösungen.",
    servicesHeroCopy: "Von Talent Sourcing bis Dokumentenunterstützung und Integration sind unsere Leistungen für professionelles internationales Recruiting konzipiert.",
    servCardOneTitle: "Internationale Personalvermittlung",
    servCardOneCopy: "Ganzheitliche Unterstützung für Unternehmen, die qualifizierte Fachkräfte außerhalb lokaler Märkte suchen.",
    servCardTwoTitle: "Talent Sourcing",
    servCardTwoCopy: "Gezielte Strategien zur Gewinnung motivierter Kandidaten passend zu Arbeitgeberanforderungen.",
    servCardThreeTitle: "Workforce Solutions",
    servCardThreeCopy: "Unterstützung bei Planung, Einstellung und Integration internationaler Talente.",
    servCardFourTitle: "Arbeitgeberberatung",
    servCardFourCopy: "Praktische Orientierung zu internationalen Einstellungsprozessen und Kandidatenerwartungen.",
    servDocKicker: "Dokumentation",
    servDocTitle: "Unterstützung mit Behörden und erforderlicher Kommunikation.",
    servDocCopy: "Wir helfen bei der Koordination mit relevanten Stellen, einschließlich der Ausländerbehörde, wenn der Recruiting-Prozess dies erfordert.",
    faqKicker: "FAQ",
    faqTitle: "Fragen, die Arbeitgeber und Kandidaten häufig stellen.",
    faqOneTitle: "Unterstützen Sie den gesamten Prozess?",
    faqOneCopy: "Ja. Wir unterstützen Recruiting, Kandidatenkommunikation, Dokumentenübersicht und Onboarding-Vorbereitung.",
    faqTwoTitle: "Helfen Sie Kandidaten bei der Relocation?",
    faqTwoCopy: "Ja. Wir bieten Relocation-Orientierung und Integrationsbegleitung für Kandidaten, die in Deutschland arbeiten möchten.",
    faqThreeTitle: "Arbeiten Sie mit Arbeitgebern?",
    faqThreeCopy: "Ja. Wir helfen Arbeitgebern, Bedarf zu definieren, Kandidaten zu finden und den Einstellungsprozess vorzubereiten.",
    faqFourTitle: "Wie starten wir?",
    faqFourCopy: "Senden Sie eine kurze Anfrage über die Kontaktseite und wir melden uns mit den nächsten Schritten.",
    contactEyebrow: "Kontakt",
    contactHeroTitle: "Lassen Sie uns über Ihre Recruiting-Ziele sprechen.",
    contactHeroCopy: "Senden Sie eine Anfrage als Arbeitgeber, Kandidat oder Partner. Das Formular öffnet Ihre E-Mail-App mit einer vorbereiteten Nachricht.",
    contactPanelTitle: "München, Deutschland",
    contactEmailLabel: "E-Mail:",
    contactLocation: "Standort: München, Deutschland",
    contactServicesLine: "Leistungen: Arbeitgeber, Kandidaten, Recruiting und Relocation-Support",
    formName: "Name",
    formEmail: "E-Mail",
    formPhone: "Telefon",
    formType: "Ich kontaktiere als",
    formTypeEmployer: "Arbeitgeber",
    formTypeCandidate: "Kandidat",
    formTypeOther: "Sonstiges",
    formSubject: "Betreff",
    formMessage: "Nachricht",
    formSubmit: "Anfrage senden",
    formNote: "Dieses statische GitHub Pages Formular öffnet Ihre E-Mail-App. Später können wir Formspree oder einen anderen Service für direkte Zustellung verbinden.",
    footerRights: "© 2026 Talorynex International Recruiting. Alle Rechte vorbehalten.",
    footerShort: "© 2026 Talorynex International Recruiting."
  }
};

const navToggle = document.querySelector(".nav-toggle");
const navMenu = document.querySelector(".nav-menu");

if (navToggle && navMenu) {
  navToggle.addEventListener("click", () => {
    const isOpen = navToggle.getAttribute("aria-expanded") === "true";
    navToggle.setAttribute("aria-expanded", String(!isOpen));
    navMenu.classList.toggle("is-open", !isOpen);
  });
}

const languageButtons = document.querySelectorAll("[data-lang]");
const translatable = document.querySelectorAll("[data-i18n]");

function applyLanguage(language) {
  const dictionary = translations[language] || translations.en;
  document.documentElement.lang = language === "bs" ? "bs" : language;

  translatable.forEach((element) => {
    const key = element.dataset.i18n;
    if (dictionary[key]) {
      element.textContent = dictionary[key];
    }
  });

  languageButtons.forEach((button) => {
    const active = button.dataset.lang === language;
    button.classList.toggle("is-active", active);
    button.setAttribute("aria-pressed", String(active));
  });

  localStorage.setItem("talorynex-language", language);
}

languageButtons.forEach((button) => {
  button.addEventListener("click", () => applyLanguage(button.dataset.lang));
});

applyLanguage(localStorage.getItem("talorynex-language") || "en");

const contactForm = document.querySelector("#contact-form");

if (contactForm) {
  contactForm.addEventListener("submit", (event) => {
    event.preventDefault();
    const formData = new FormData(contactForm);
    const subject = formData.get("subject") || "Talorynex inquiry";
    const body = [
      `Name: ${formData.get("name") || ""}`,
      `Email: ${formData.get("email") || ""}`,
      `Phone: ${formData.get("phone") || ""}`,
      `Inquiry type: ${formData.get("type") || ""}`,
      "",
      "Message:",
      formData.get("message") || ""
    ].join("\n");

    window.location.href = `mailto:info@talorynex-international-recruiting.de?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
  });
}
